services:
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: unless-stopped

    command:
      - --configFile=/etc/traefik/traefik.yml

    ports:
      - "80:80"
      - "443:443"

    networks:
      - proxy

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - ./traefik/certs:/certs

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped

    env_file:
      - .env

    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      TZ: ${TZ}

    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - internal

networks:
  proxy:
    name: proxy

  internal:
    name: internal
    internal: true

volumes:
  wordpress_data:
  nextcloud_data:
  mariadb_data:
  redis_data:
  uptimekuma_data:
